import { Routes } from '@angular/router';
import { authGuard } from './core/guards/auth.guard';
import { LayoutComponent } from './layout/layout.component';
import { LoginComponent } from './auth/login.component';

export const routes: Routes = [
  { path: 'login', component: LoginComponent },
  {
    path: '',
    component: LayoutComponent,
    canActivate: [authGuard],
    children: [
      { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'dashboard', loadComponent: () => import('./pages/dashboard/dashboard.component').then(m => m.DashboardComponent) },
      { path: 'visitors', loadComponent: () => import('./pages/visitors/visitors.component').then(m => m.VisitorsComponent) },
      { path: 'daily-help', loadComponent: () => import('./pages/daily-help/daily-help.component').then(m => m.DailyHelpComponent) },
      { path: 'staff', loadComponent: () => import('./pages/staff/staff.component').then(m => m.StaffComponent) },
      { path: 'complaints', loadComponent: () => import('./pages/complaints/complaints.component').then(m => m.ComplaintsComponent) },
      { path: 'helpdesk', loadComponent: () => import('./pages/helpdesk/helpdesk.component').then(m => m.HelpdeskComponent) },
      { path: 'alerts', loadComponent: () => import('./pages/alerts/alerts.component').then(m => m.AlertsComponent) },
      { path: 'deliveries', loadComponent: () => import('./pages/deliveries/deliveries.component').then(m => m.DeliveriesComponent) },
      { path: 'vehicles', loadComponent: () => import('./pages/vehicles/vehicles.component').then(m => m.VehiclesComponent) },
      { path: 'patrol', loadComponent: () => import('./pages/patrol/patrol.component').then(m => m.PatrolComponent) },
      { path: 'incidents', loadComponent: () => import('./pages/incidents/incidents.component').then(m => m.IncidentsComponent) },
      { path: 'notes-to-guard', loadComponent: () => import('./pages/notes-to-guard/notes-to-guard.component').then(m => m.NotesToGuardComponent) },
      { path: 'activity-logs', loadComponent: () => import('./pages/activity-logs/activity-logs.component').then(m => m.ActivityLogsComponent) },
      { path: 'residents', loadComponent: () => import('./pages/residents/residents.component').then(m => m.ResidentsComponent) },
      { path: 'units', loadComponent: () => import('./pages/units/units.component').then(m => m.UnitsComponent) },
      { path: 'notices', loadComponent: () => import('./pages/notices/notices.component').then(m => m.NoticesComponent) },
      { path: 'amenities', loadComponent: () => import('./pages/amenities/amenities.component').then(m => m.AmenitiesComponent) },
      { path: 'directory', loadComponent: () => import('./pages/directory/directory.component').then(m => m.DirectoryComponent) },
      { path: 'billing', loadComponent: () => import('./pages/billing/billing.component').then(m => m.BillingComponent) },
      { path: 'polls', loadComponent: () => import('./pages/polls/polls.component').then(m => m.PollsComponent) },
      { path: 'committee', loadComponent: () => import('./pages/committee/committee.component').then(m => m.CommitteeComponent) },
      { path: 'settings', loadComponent: () => import('./pages/settings/settings.component').then(m => m.SettingsComponent) },
      // Super Admin pages
      { path: 'societies', loadComponent: () => import('./pages/societies/societies.component').then(m => m.SocietiesComponent) },
      { path: 'daily-help-setup', loadComponent: () => import('./pages/daily-help-setup/daily-help-setup.component').then(m => m.DailyHelpSetupComponent) },
      { path: 'mass-upload', loadComponent: () => import('./pages/mass-upload/mass-upload.component').then(m => m.MassUploadComponent) },
      // New feature pages
      { path: 'qr-code', loadComponent: () => import('./pages/qr-code/qr-code.component').then(m => m.QrCodeComponent) },
      { path: 'emergency-contacts', loadComponent: () => import('./pages/emergency-contacts/emergency-contacts.component').then(m => m.EmergencyContactsComponent) },
      { path: 'community-setup', loadComponent: () => import('./pages/community-setup/community-setup.component').then(m => m.CommunitySetupComponent) },
      { path: 'security-shifts', loadComponent: () => import('./pages/security-shifts/security-shifts.component').then(m => m.SecurityShiftsComponent) },
      { path: 'local-services', loadComponent: () => import('./pages/local-services/local-services.component').then(m => m.LocalServicesComponent) },
      // Additional feature pages
      { path: 'advertisements', loadComponent: () => import('./pages/advertisements/advertisements.component').then(m => m.AdvertisementsComponent) },
      { path: 'anpr', loadComponent: () => import('./pages/anpr/anpr.component').then(m => m.AnprComponent) },
      { path: 'attendance', loadComponent: () => import('./pages/attendance/attendance.component').then(m => m.AttendanceComponent) },
      { path: 'carpooling', loadComponent: () => import('./pages/carpooling/carpooling.component').then(m => m.CarpoolingComponent) },
      { path: 'daily-essentials', loadComponent: () => import('./pages/daily-essentials/daily-essentials.component').then(m => m.DailyEssentialsComponent) },
      { path: 'documents', loadComponent: () => import('./pages/documents/documents.component').then(m => m.DocumentsComponent) },
      { path: 'domestic-staff', loadComponent: () => import('./pages/domestic-staff/domestic-staff.component').then(m => m.DomesticStaffComponent) },
      { path: 'events', loadComponent: () => import('./pages/events/events.component').then(m => m.EventsComponent) },
      { path: 'face-recognition', loadComponent: () => import('./pages/face-recognition/face-recognition.component').then(m => m.FaceRecognitionComponent) },
      { path: 'finance', loadComponent: () => import('./pages/finance/finance.component').then(m => m.FinanceComponent) },
      { path: 'forum', loadComponent: () => import('./pages/forum/forum.component').then(m => m.ForumComponent) },
      { path: 'group-discussion', loadComponent: () => import('./pages/group-discussion/group-discussion.component').then(m => m.GroupDiscussionComponent) },
      { path: 'intercom', loadComponent: () => import('./pages/intercom/intercom.component').then(m => m.IntercomComponent) },
      { path: 'lost-found', loadComponent: () => import('./pages/lost-found/lost-found.component').then(m => m.LostFoundComponent) },
      { path: 'marketplace', loadComponent: () => import('./pages/marketplace/marketplace.component').then(m => m.MarketplaceComponent) },
      { path: 'move-in-out', loadComponent: () => import('./pages/move-in-out/move-in-out.component').then(m => m.MoveInOutComponent) },
      { path: 'parking', loadComponent: () => import('./pages/parking/parking.component').then(m => m.ParkingComponent) },
      { path: 'pet', loadComponent: () => import('./pages/pet/pet.component').then(m => m.PetComponent) },
      { path: 'rental-agreement', loadComponent: () => import('./pages/rental-agreement/rental-agreement.component').then(m => m.RentalAgreementComponent) },
      { path: 'reports', loadComponent: () => import('./pages/reports/reports.component').then(m => m.ReportsComponent) },
      { path: 'school-bus', loadComponent: () => import('./pages/school-bus/school-bus.component').then(m => m.SchoolBusComponent) },
      { path: 'skill-exchange', loadComponent: () => import('./pages/skill-exchange/skill-exchange.component').then(m => m.SkillExchangeComponent) },
      { path: 'sla', loadComponent: () => import('./pages/sla/sla.component').then(m => m.SlaComponent) },
      { path: 'staff-leave', loadComponent: () => import('./pages/staff-leave/staff-leave.component').then(m => m.StaffLeaveComponent) },
      { path: 'vendor', loadComponent: () => import('./pages/vendor/vendor.component').then(m => m.VendorComponent) },
    ]
  },
  { path: '**', redirectTo: 'dashboard' }
];
